annotations:
  artifacthub.io/changes: |-
    - "Chores: Align security contacts & chart maintainers to actual owners. (#11480)"
    - "Fix helm install on cloud provider admonition block (#11412)"
    - "edited helm-install tips (#11411)"
    - "added info for aws helm install (#11410)"
    - "add workflow to helm release and update ct for branch (#11317)"
    - "Merge pull request #11277 from strongjz/chart-1.10.1 (#11314)"
    - "release helm chart from release branch (#11278)"
    - "update post submit helm ci and clean up (#11221)"
    - "refactor helm ci tests part I (#11188)"
    - "Update Ingress-Nginx version controller-v1.10.2"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.10.2
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.21.0-0'
maintainers:
- name: cpanato
- name: Gacko
- name: puerco
- name: rikatz
- name: strongjz
- name: tao12345666333
name: ingress-nginx
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.10.2
